#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./app"
  delay = 500
  exclude_dir = ["tmp", "vendor", "testdata", "node_modules"]
  exclude_regex = ["_test\\.go"]
  include_dir = ["app", "internal", "pkg", "ui"]
  include_ext = ["go", "tmpl", "html", "css", "js"]
  kill_delay = "500ms"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  app_start_timeout = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
